Viweb\SyliusProductBridgeBundle\Entity\CategoryTranslation:
    type: entity
    table: product_category_translation
    repositoryClass: Viweb\SyliusProductBridgeBundle\Repository\CategoryTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        body:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
