Viweb\SyliusProductBridgeBundle\Entity\Product:
    type: entity
    table: sylius_product

    manyToOne:
        category:
            targetEntity: Viweb\SyliusProductBridgeBundle\Entity\Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
        mainImage:
            targetEntity: Viweb\MediaBundle\Entity\Media
            joinColumn:
                name: media_id
                referencedColumnName: id
        secondaryImage:
            targetEntity: Viweb\MediaBundle\Entity\Media
            joinColumn:
                name: media_id
                referencedColumnName: id