viweb_sylius_product_bridge_homepage:
    path:     /
    defaults: { _controller: ViwebSyliusProductBridgeBundle:Default:index }
viweb_sylius_product_bridge_search:
    path:     /search/results
    defaults: { _controller: ViwebSyliusProductBridgeBundle:Frontend:search }