<?php

namespace Viweb\SyliusProductBridgeBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findBySlug($slug, $locale = 'fr')
    {
        return $this->createQueryBuilder('c')
            ->select('c', 'ct')
            ->innerJoin('c.translations', 'ct')
            ->andWhere('ct.slug LIKE :slug')
            ->andWhere('ct.locale = :locale')
            ->setParameter('slug', $slug)
            ->setParameter('locale', $locale)
            ->getQuery()->getSingleResult();
    }
}
