<?php

namespace Viweb\SyliusProductBridgeBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findBySlug($slug, $locale = 'fr', $maker = null)
    {

        $qb =$this->createQueryBuilder('c')
            ->select('c', 'ct')
            ->innerJoin('c.translations', 'ct')
            ->andWhere('ct.slug LIKE :slug')
            ->andWhere('ct.locale = :locale')
            ->setParameter('slug', $slug)
            ->setParameter('locale', $locale);
        if($maker){
            $qb->innerJoin('c.products', 'p')
                ->innerJoin('p.attributes', 'pa')
                ->andWhere('pa.text like :maker')
                ->setParameter('maker', $maker);
        }
        return  $qb->getQuery()->getSingleResult();
    }

    public function findForMenuBuilder()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c', 'ct')
            ->innerJoin('c.translations', 'ct')
            ->andWhere('ct.locale = :locale')
            ->setParameter('locale', $locale);
    }
}
